"""Tactical multi-domain simulation engine (Layer 1 of MARL system)."""

from .config import (
    AC1_AMMO_CANNON,
    AC1_AMMO_ROCKET,
    AC1_ANGULAR_VELOCITY_RANGE_DEG,
    AC1_HIT_PROB_CANNON,
    AC1_SPEED_RANGE_KNOTS,
    AC1_WEZ_ANGLE_DEG,
    AC1_WEZ_RANGE_KM,
    AC2_AMMO_CANNON,
    AC2_AMMO_ROCKET,
    AC2_ANGULAR_VELOCITY_RANGE_DEG,
    AC2_HIT_PROB_CANNON,
    AC2_SPEED_RANGE_KNOTS,
    AC2_WEZ_ANGLE_DEG,
    AC2_WEZ_RANGE_KM,
    DEFAULT_DT_SECONDS,
    DEFAULT_EPISODE_HORIZON,
    DEFAULT_LEVEL5_HORIZON,
    DEFAULT_MAP_SIZE_KM,
    DEFAULT_SEED,
    GROUND_AMMO,
    GROUND_HIT_PROB,
    GROUND_SENSOR_RANGE_KM,
    GROUND_SPEED_RANGE_KMPH,
    GROUND_WEZ_RANGE_KM,
    HIGH_LEVEL_MAP_SIZE_KM,
    MAX_ALTITUDE_KM,
    MIN_ALTITUDE_KM,
    SEA_AMMO,
    SEA_HIT_PROB,
    SEA_RADAR_RANGE_KM,
    SEA_SPEED_RANGE_KNOTS,
    SEA_WEZ_RANGE_KM,
    SENSOR_ASPECT_PENALTY,
    SENSOR_BASE_PD,
    SENSOR_FALSE_ALARM_RATE,
    SENSOR_RANGE_FALLOFF,
    WEAPON_MISS_DISTANCE_SIGMA_KM,
    WEAPON_PK_SCALE,
)
from .entities import AirEntity, GroundEntity, SeaEntity, SimEntity
from .env import TacticalEnv
from .map import Map2D
from .scenarios import ScenarioConfig, generate_scenario, spawn_entities
from .sensors import Sensor, SensorContact
from .weapons import Weapon, WeaponEffect

__all__ = [
    # Map & Environment
    "Map2D",
    "TacticalEnv",
    "ScenarioConfig",
    "generate_scenario",
    "spawn_entities",
    # Entities
    "SimEntity",
    "AirEntity",
    "GroundEntity",
    "SeaEntity",
    # Sensors & Weapons
    "Sensor",
    "SensorContact",
    "Weapon",
    "WeaponEffect",
    # Constants
    "DEFAULT_MAP_SIZE_KM",
    "HIGH_LEVEL_MAP_SIZE_KM",
    "MIN_ALTITUDE_KM",
    "MAX_ALTITUDE_KM",
    "DEFAULT_DT_SECONDS",
    "DEFAULT_EPISODE_HORIZON",
    "DEFAULT_LEVEL5_HORIZON",
    "AC1_ANGULAR_VELOCITY_RANGE_DEG",
    "AC1_SPEED_RANGE_KNOTS",
    "AC1_WEZ_ANGLE_DEG",
    "AC1_WEZ_RANGE_KM",
    "AC1_HIT_PROB_CANNON",
    "AC1_AMMO_CANNON",
    "AC1_AMMO_ROCKET",
    "AC2_ANGULAR_VELOCITY_RANGE_DEG",
    "AC2_SPEED_RANGE_KNOTS",
    "AC2_WEZ_ANGLE_DEG",
    "AC2_WEZ_RANGE_KM",
    "AC2_HIT_PROB_CANNON",
    "AC2_AMMO_CANNON",
    "AC2_AMMO_ROCKET",
    "GROUND_SPEED_RANGE_KMPH",
    "GROUND_WEZ_RANGE_KM",
    "GROUND_HIT_PROB",
    "GROUND_AMMO",
    "GROUND_SENSOR_RANGE_KM",
    "SEA_SPEED_RANGE_KNOTS",
    "SEA_WEZ_RANGE_KM",
    "SEA_HIT_PROB",
    "SEA_AMMO",
    "SEA_RADAR_RANGE_KM",
    "SENSOR_BASE_PD",
    "SENSOR_RANGE_FALLOFF",
    "SENSOR_ASPECT_PENALTY",
    "SENSOR_FALSE_ALARM_RATE",
    "WEAPON_PK_SCALE",
    "WEAPON_MISS_DISTANCE_SIGMA_KM",
    "DEFAULT_SEED",
]
